### PR TITLE
[SNAP-53] Expand the permitted characters in the service param.

### PR DESCRIPTION
**Pull request by cafuego**
This way, properties that have hyphenated names can pass that name directly. Also allow full stops and underscores.

The service parameter is now validated using a regex.

### CODE REVIEW

**Comment by cafuego** [comment]
D'oh. Pushed this before I noticed https://github.com/UN-OCHA/tools-snap-service/pull/56. Shall we use this one anyway, as it also allows hyphens and full stops?

**Comment by guillaumev** [comment]
@cafuego When I modified "hid-api" to "hidapi" in the HID API to be able to use snap, @teodorescuserban told me that you were trying to keep service names standard in anticipation to the AWS migration. I'm not sure if AWS is going to allow service names with hyphens and periods. If it does, then let's merge your PR. If it doesn't however, I would say let's keep only underscores allowed....

**Comment by rupl** [comment]
Closing in favor of #56

**Comment by cafuego** [comment]
I insist.

**Comment by rupl** [comment]
denied

(fixed in another PR)

**Pull request closed without merging**
