### PR TITLE
chore: Version bump.

### PR DESCRIPTION
**Pull request by cafuego**
* nodejs v22
* Newer pm2 and ws versions
* New puppeteer version

Refs: OPS-10552

### CODE REVIEW

**Comment by cafuego** [comment]
I can't run it with `chrome` locally, as I'm on apple silicon. However, it seems to work fine with `chromium` if I override the browser or puppeteer as per the docs.

**Comment by lazysoundsystem** [comment]
Seems to run okay, but this is the contents of the test.pdf created as per the instructions in CONTRIBUTING.md:
```
{"errors":[{"msg":"Must be an alphanumeric string identifier (hyphens, underscores are also allowed).","param":"service","location":"query"}]}
```
There are a few warnings about elastic_apm_node in the logs, but I'll try some more on this later today.

**Review by lazysoundsystem — APPROVED** [review]
Approving so as not to block things (if it's working for you on Chromium) - will continue tomorrow to try to work out the error message.

**Comment by cafuego** [comment]
The apm module can go, don't worry about it.

As for the error you got, adding a `?service=x` param will sort that. I'll update the doc.

**Pull request merged**
