### PR TITLE
SNAP-40: custom header/footer

### PR DESCRIPTION
**Pull request by rupl**
## https://humanitarian.atlassian.net/browse/SNAP-40

We're a shared service, not a pet project. Snap used to have all sorts of hardcoded stuff for DSR and this PR gets us back on track for adoption by other sites that have different branding requirements.

⚠️ **This PR contains breaking changes** that mostly one person — myself — needs to be aware of. 

But just FYI @cafuego we'll need to deploy the changes inside https://github.com/UN-OCHA/reports-site/pull/144 before this branch goes out to prod, in order to maintain stability on SitRep site.

### CODE REVIEW

**Comment by rupl** [comment]
I'm also waiting to merge this until I can try our DSR dev against current Snap dev, as a sort of pre-deploy test.

**Comment by rupl** [comment]
Everything looking good so I'm going to try merging this to dev and see how PDFs look on our staging.

**Comment by cafuego** [comment]
Ok. Mind you, I wouldn't do a prod deploy for snap service unless someone specifically told me to.

**Comment by rupl** [comment]
cool, I was just trying to explain things out of an abundance of caution.

**Comment by cafuego** [comment]
I'm going to interpret that as "please do a deploy now" and also YOLO 🤪

**Pull request merged**
